// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"github.com/gabkaclassic/GitQuest/internal/dto"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAchievementRepository creates a new instance of MockAchievementRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAchievementRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAchievementRepository {
	mock := &MockAchievementRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAchievementRepository is an autogenerated mock type for the AchievementRepository type
type MockAchievementRepository struct {
	mock.Mock
}

type MockAchievementRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAchievementRepository) EXPECT() *MockAchievementRepository_Expecter {
	return &MockAchievementRepository_Expecter{mock: &_m.Mock}
}

// ExistsInAllTime provides a mock function for the type MockAchievementRepository
func (_mock *MockAchievementRepository) ExistsInAllTime(achievement *dto.Achievement) (bool, error) {
	ret := _mock.Called(achievement)

	if len(ret) == 0 {
		panic("no return value specified for ExistsInAllTime")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*dto.Achievement) (bool, error)); ok {
		return returnFunc(achievement)
	}
	if returnFunc, ok := ret.Get(0).(func(*dto.Achievement) bool); ok {
		r0 = returnFunc(achievement)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(*dto.Achievement) error); ok {
		r1 = returnFunc(achievement)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAchievementRepository_ExistsInAllTime_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsInAllTime'
type MockAchievementRepository_ExistsInAllTime_Call struct {
	*mock.Call
}

// ExistsInAllTime is a helper method to define mock.On call
//   - achievement *dto.Achievement
func (_e *MockAchievementRepository_Expecter) ExistsInAllTime(achievement interface{}) *MockAchievementRepository_ExistsInAllTime_Call {
	return &MockAchievementRepository_ExistsInAllTime_Call{Call: _e.mock.On("ExistsInAllTime", achievement)}
}

func (_c *MockAchievementRepository_ExistsInAllTime_Call) Run(run func(achievement *dto.Achievement)) *MockAchievementRepository_ExistsInAllTime_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *dto.Achievement
		if args[0] != nil {
			arg0 = args[0].(*dto.Achievement)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAchievementRepository_ExistsInAllTime_Call) Return(b bool, err error) *MockAchievementRepository_ExistsInAllTime_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockAchievementRepository_ExistsInAllTime_Call) RunAndReturn(run func(achievement *dto.Achievement) (bool, error)) *MockAchievementRepository_ExistsInAllTime_Call {
	_c.Call.Return(run)
	return _c
}

// ReevalByRuleDiff provides a mock function for the type MockAchievementRepository
func (_mock *MockAchievementRepository) ReevalByRuleDiff(ruleDiff *dto.RuleDiff) ([]string, error) {
	ret := _mock.Called(ruleDiff)

	if len(ret) == 0 {
		panic("no return value specified for ReevalByRuleDiff")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*dto.RuleDiff) ([]string, error)); ok {
		return returnFunc(ruleDiff)
	}
	if returnFunc, ok := ret.Get(0).(func(*dto.RuleDiff) []string); ok {
		r0 = returnFunc(ruleDiff)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*dto.RuleDiff) error); ok {
		r1 = returnFunc(ruleDiff)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAchievementRepository_ReevalByRuleDiff_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReevalByRuleDiff'
type MockAchievementRepository_ReevalByRuleDiff_Call struct {
	*mock.Call
}

// ReevalByRuleDiff is a helper method to define mock.On call
//   - ruleDiff *dto.RuleDiff
func (_e *MockAchievementRepository_Expecter) ReevalByRuleDiff(ruleDiff interface{}) *MockAchievementRepository_ReevalByRuleDiff_Call {
	return &MockAchievementRepository_ReevalByRuleDiff_Call{Call: _e.mock.On("ReevalByRuleDiff", ruleDiff)}
}

func (_c *MockAchievementRepository_ReevalByRuleDiff_Call) Run(run func(ruleDiff *dto.RuleDiff)) *MockAchievementRepository_ReevalByRuleDiff_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *dto.RuleDiff
		if args[0] != nil {
			arg0 = args[0].(*dto.RuleDiff)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAchievementRepository_ReevalByRuleDiff_Call) Return(strings []string, err error) *MockAchievementRepository_ReevalByRuleDiff_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockAchievementRepository_ReevalByRuleDiff_Call) RunAndReturn(run func(ruleDiff *dto.RuleDiff) ([]string, error)) *MockAchievementRepository_ReevalByRuleDiff_Call {
	_c.Call.Return(run)
	return _c
}

// SaveAll provides a mock function for the type MockAchievementRepository
func (_mock *MockAchievementRepository) SaveAll(achievements []dto.Achievement) error {
	ret := _mock.Called(achievements)

	if len(ret) == 0 {
		panic("no return value specified for SaveAll")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]dto.Achievement) error); ok {
		r0 = returnFunc(achievements)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAchievementRepository_SaveAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveAll'
type MockAchievementRepository_SaveAll_Call struct {
	*mock.Call
}

// SaveAll is a helper method to define mock.On call
//   - achievements []dto.Achievement
func (_e *MockAchievementRepository_Expecter) SaveAll(achievements interface{}) *MockAchievementRepository_SaveAll_Call {
	return &MockAchievementRepository_SaveAll_Call{Call: _e.mock.On("SaveAll", achievements)}
}

func (_c *MockAchievementRepository_SaveAll_Call) Run(run func(achievements []dto.Achievement)) *MockAchievementRepository_SaveAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []dto.Achievement
		if args[0] != nil {
			arg0 = args[0].([]dto.Achievement)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAchievementRepository_SaveAll_Call) Return(err error) *MockAchievementRepository_SaveAll_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAchievementRepository_SaveAll_Call) RunAndReturn(run func(achievements []dto.Achievement) error) *MockAchievementRepository_SaveAll_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEventRepository creates a new instance of MockEventRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventRepository {
	mock := &MockEventRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEventRepository is an autogenerated mock type for the EventRepository type
type MockEventRepository struct {
	mock.Mock
}

type MockEventRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEventRepository) EXPECT() *MockEventRepository_Expecter {
	return &MockEventRepository_Expecter{mock: &_m.Mock}
}

// GetAllUsersWithEvents provides a mock function for the type MockEventRepository
func (_mock *MockEventRepository) GetAllUsersWithEvents() ([]string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllUsersWithEvents")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEventRepository_GetAllUsersWithEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllUsersWithEvents'
type MockEventRepository_GetAllUsersWithEvents_Call struct {
	*mock.Call
}

// GetAllUsersWithEvents is a helper method to define mock.On call
func (_e *MockEventRepository_Expecter) GetAllUsersWithEvents() *MockEventRepository_GetAllUsersWithEvents_Call {
	return &MockEventRepository_GetAllUsersWithEvents_Call{Call: _e.mock.On("GetAllUsersWithEvents")}
}

func (_c *MockEventRepository_GetAllUsersWithEvents_Call) Run(run func()) *MockEventRepository_GetAllUsersWithEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEventRepository_GetAllUsersWithEvents_Call) Return(strings []string, err error) *MockEventRepository_GetAllUsersWithEvents_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockEventRepository_GetAllUsersWithEvents_Call) RunAndReturn(run func() ([]string, error)) *MockEventRepository_GetAllUsersWithEvents_Call {
	_c.Call.Return(run)
	return _c
}

// SaveAll provides a mock function for the type MockEventRepository
func (_mock *MockEventRepository) SaveAll(events []dto.Event) error {
	ret := _mock.Called(events)

	if len(ret) == 0 {
		panic("no return value specified for SaveAll")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]dto.Event) error); ok {
		r0 = returnFunc(events)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEventRepository_SaveAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveAll'
type MockEventRepository_SaveAll_Call struct {
	*mock.Call
}

// SaveAll is a helper method to define mock.On call
//   - events []dto.Event
func (_e *MockEventRepository_Expecter) SaveAll(events interface{}) *MockEventRepository_SaveAll_Call {
	return &MockEventRepository_SaveAll_Call{Call: _e.mock.On("SaveAll", events)}
}

func (_c *MockEventRepository_SaveAll_Call) Run(run func(events []dto.Event)) *MockEventRepository_SaveAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []dto.Event
		if args[0] != nil {
			arg0 = args[0].([]dto.Event)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEventRepository_SaveAll_Call) Return(err error) *MockEventRepository_SaveAll_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEventRepository_SaveAll_Call) RunAndReturn(run func(events []dto.Event) error) *MockEventRepository_SaveAll_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRuleRepository creates a new instance of MockRuleRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRuleRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRuleRepository {
	mock := &MockRuleRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRuleRepository is an autogenerated mock type for the RuleRepository type
type MockRuleRepository struct {
	mock.Mock
}

type MockRuleRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRuleRepository) EXPECT() *MockRuleRepository_Expecter {
	return &MockRuleRepository_Expecter{mock: &_m.Mock}
}

// GetLastRule provides a mock function for the type MockRuleRepository
func (_mock *MockRuleRepository) GetLastRule(s string) (*dto.Rule, error) {
	ret := _mock.Called(s)

	if len(ret) == 0 {
		panic("no return value specified for GetLastRule")
	}

	var r0 *dto.Rule
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*dto.Rule, error)); ok {
		return returnFunc(s)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *dto.Rule); ok {
		r0 = returnFunc(s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.Rule)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(s)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRuleRepository_GetLastRule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLastRule'
type MockRuleRepository_GetLastRule_Call struct {
	*mock.Call
}

// GetLastRule is a helper method to define mock.On call
//   - s string
func (_e *MockRuleRepository_Expecter) GetLastRule(s interface{}) *MockRuleRepository_GetLastRule_Call {
	return &MockRuleRepository_GetLastRule_Call{Call: _e.mock.On("GetLastRule", s)}
}

func (_c *MockRuleRepository_GetLastRule_Call) Run(run func(s string)) *MockRuleRepository_GetLastRule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRuleRepository_GetLastRule_Call) Return(rule *dto.Rule, err error) *MockRuleRepository_GetLastRule_Call {
	_c.Call.Return(rule, err)
	return _c
}

func (_c *MockRuleRepository_GetLastRule_Call) RunAndReturn(run func(s string) (*dto.Rule, error)) *MockRuleRepository_GetLastRule_Call {
	_c.Call.Return(run)
	return _c
}

// GetRule provides a mock function for the type MockRuleRepository
func (_mock *MockRuleRepository) GetRule(s string, s1 string) (*dto.Rule, error) {
	ret := _mock.Called(s, s1)

	if len(ret) == 0 {
		panic("no return value specified for GetRule")
	}

	var r0 *dto.Rule
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (*dto.Rule, error)); ok {
		return returnFunc(s, s1)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) *dto.Rule); ok {
		r0 = returnFunc(s, s1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.Rule)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(s, s1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRuleRepository_GetRule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRule'
type MockRuleRepository_GetRule_Call struct {
	*mock.Call
}

// GetRule is a helper method to define mock.On call
//   - s string
//   - s1 string
func (_e *MockRuleRepository_Expecter) GetRule(s interface{}, s1 interface{}) *MockRuleRepository_GetRule_Call {
	return &MockRuleRepository_GetRule_Call{Call: _e.mock.On("GetRule", s, s1)}
}

func (_c *MockRuleRepository_GetRule_Call) Run(run func(s string, s1 string)) *MockRuleRepository_GetRule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRuleRepository_GetRule_Call) Return(rule *dto.Rule, err error) *MockRuleRepository_GetRule_Call {
	_c.Call.Return(rule, err)
	return _c
}

func (_c *MockRuleRepository_GetRule_Call) RunAndReturn(run func(s string, s1 string) (*dto.Rule, error)) *MockRuleRepository_GetRule_Call {
	_c.Call.Return(run)
	return _c
}

// SaveAll provides a mock function for the type MockRuleRepository
func (_mock *MockRuleRepository) SaveAll(rules []dto.Rule) error {
	ret := _mock.Called(rules)

	if len(ret) == 0 {
		panic("no return value specified for SaveAll")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]dto.Rule) error); ok {
		r0 = returnFunc(rules)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRuleRepository_SaveAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveAll'
type MockRuleRepository_SaveAll_Call struct {
	*mock.Call
}

// SaveAll is a helper method to define mock.On call
//   - rules []dto.Rule
func (_e *MockRuleRepository_Expecter) SaveAll(rules interface{}) *MockRuleRepository_SaveAll_Call {
	return &MockRuleRepository_SaveAll_Call{Call: _e.mock.On("SaveAll", rules)}
}

func (_c *MockRuleRepository_SaveAll_Call) Run(run func(rules []dto.Rule)) *MockRuleRepository_SaveAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []dto.Rule
		if args[0] != nil {
			arg0 = args[0].([]dto.Rule)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRuleRepository_SaveAll_Call) Return(err error) *MockRuleRepository_SaveAll_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRuleRepository_SaveAll_Call) RunAndReturn(run func(rules []dto.Rule) error) *MockRuleRepository_SaveAll_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserRepository creates a new instance of MockUserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserRepository {
	mock := &MockUserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserRepository is an autogenerated mock type for the UserRepository type
type MockUserRepository struct {
	mock.Mock
}

type MockUserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserRepository) EXPECT() *MockUserRepository_Expecter {
	return &MockUserRepository_Expecter{mock: &_m.Mock}
}

// ExistsByEmail provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) ExistsByEmail(email string) (bool, error) {
	ret := _mock.Called(email)

	if len(ret) == 0 {
		panic("no return value specified for ExistsByEmail")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (bool, error)); ok {
		return returnFunc(email)
	}
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(email)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_ExistsByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExistsByEmail'
type MockUserRepository_ExistsByEmail_Call struct {
	*mock.Call
}

// ExistsByEmail is a helper method to define mock.On call
//   - email string
func (_e *MockUserRepository_Expecter) ExistsByEmail(email interface{}) *MockUserRepository_ExistsByEmail_Call {
	return &MockUserRepository_ExistsByEmail_Call{Call: _e.mock.On("ExistsByEmail", email)}
}

func (_c *MockUserRepository_ExistsByEmail_Call) Run(run func(email string)) *MockUserRepository_ExistsByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserRepository_ExistsByEmail_Call) Return(b bool, err error) *MockUserRepository_ExistsByEmail_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockUserRepository_ExistsByEmail_Call) RunAndReturn(run func(email string) (bool, error)) *MockUserRepository_ExistsByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// GetPasswordByEmail provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) GetPasswordByEmail(email string) (string, error) {
	ret := _mock.Called(email)

	if len(ret) == 0 {
		panic("no return value specified for GetPasswordByEmail")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(email)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(email)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(email)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_GetPasswordByEmail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPasswordByEmail'
type MockUserRepository_GetPasswordByEmail_Call struct {
	*mock.Call
}

// GetPasswordByEmail is a helper method to define mock.On call
//   - email string
func (_e *MockUserRepository_Expecter) GetPasswordByEmail(email interface{}) *MockUserRepository_GetPasswordByEmail_Call {
	return &MockUserRepository_GetPasswordByEmail_Call{Call: _e.mock.On("GetPasswordByEmail", email)}
}

func (_c *MockUserRepository_GetPasswordByEmail_Call) Run(run func(email string)) *MockUserRepository_GetPasswordByEmail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserRepository_GetPasswordByEmail_Call) Return(s string, err error) *MockUserRepository_GetPasswordByEmail_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockUserRepository_GetPasswordByEmail_Call) RunAndReturn(run func(email string) (string, error)) *MockUserRepository_GetPasswordByEmail_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockUserRepository
func (_mock *MockUserRepository) Save(user *dto.User) (*uuid.UUID, error) {
	ret := _mock.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 *uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*dto.User) (*uuid.UUID, error)); ok {
		return returnFunc(user)
	}
	if returnFunc, ok := ret.Get(0).(func(*dto.User) *uuid.UUID); ok {
		r0 = returnFunc(user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*dto.User) error); ok {
		r1 = returnFunc(user)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockUserRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - user *dto.User
func (_e *MockUserRepository_Expecter) Save(user interface{}) *MockUserRepository_Save_Call {
	return &MockUserRepository_Save_Call{Call: _e.mock.On("Save", user)}
}

func (_c *MockUserRepository_Save_Call) Run(run func(user *dto.User)) *MockUserRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *dto.User
		if args[0] != nil {
			arg0 = args[0].(*dto.User)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserRepository_Save_Call) Return(uUID *uuid.UUID, err error) *MockUserRepository_Save_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *MockUserRepository_Save_Call) RunAndReturn(run func(user *dto.User) (*uuid.UUID, error)) *MockUserRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}
