// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package service

import (
	"context"

	"github.com/gabkaclassic/GitQuest/internal/dto"
	"github.com/gabkaclassic/metrics/pkg/error"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAchievementService creates a new instance of MockAchievementService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAchievementService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAchievementService {
	mock := &MockAchievementService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAchievementService is an autogenerated mock type for the AchievementService type
type MockAchievementService struct {
	mock.Mock
}

type MockAchievementService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAchievementService) EXPECT() *MockAchievementService_Expecter {
	return &MockAchievementService_Expecter{mock: &_m.Mock}
}

// CheckForNewAchievements provides a mock function for the type MockAchievementService
func (_mock *MockAchievementService) CheckForNewAchievements(context1 context.Context, rules *[]dto.Rule) error {
	ret := _mock.Called(context1, rules)

	if len(ret) == 0 {
		panic("no return value specified for CheckForNewAchievements")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *[]dto.Rule) error); ok {
		r0 = returnFunc(context1, rules)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAchievementService_CheckForNewAchievements_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckForNewAchievements'
type MockAchievementService_CheckForNewAchievements_Call struct {
	*mock.Call
}

// CheckForNewAchievements is a helper method to define mock.On call
//   - context1 context.Context
//   - rules *[]dto.Rule
func (_e *MockAchievementService_Expecter) CheckForNewAchievements(context1 interface{}, rules interface{}) *MockAchievementService_CheckForNewAchievements_Call {
	return &MockAchievementService_CheckForNewAchievements_Call{Call: _e.mock.On("CheckForNewAchievements", context1, rules)}
}

func (_c *MockAchievementService_CheckForNewAchievements_Call) Run(run func(context1 context.Context, rules *[]dto.Rule)) *MockAchievementService_CheckForNewAchievements_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *[]dto.Rule
		if args[1] != nil {
			arg1 = args[1].(*[]dto.Rule)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAchievementService_CheckForNewAchievements_Call) Return(err error) *MockAchievementService_CheckForNewAchievements_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAchievementService_CheckForNewAchievements_Call) RunAndReturn(run func(context1 context.Context, rules *[]dto.Rule) error) *MockAchievementService_CheckForNewAchievements_Call {
	_c.Call.Return(run)
	return _c
}

// ReevalByDiffs provides a mock function for the type MockAchievementService
func (_mock *MockAchievementService) ReevalByDiffs(ruleDiffs *[]dto.RuleDiff) error {
	ret := _mock.Called(ruleDiffs)

	if len(ret) == 0 {
		panic("no return value specified for ReevalByDiffs")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*[]dto.RuleDiff) error); ok {
		r0 = returnFunc(ruleDiffs)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAchievementService_ReevalByDiffs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReevalByDiffs'
type MockAchievementService_ReevalByDiffs_Call struct {
	*mock.Call
}

// ReevalByDiffs is a helper method to define mock.On call
//   - ruleDiffs *[]dto.RuleDiff
func (_e *MockAchievementService_Expecter) ReevalByDiffs(ruleDiffs interface{}) *MockAchievementService_ReevalByDiffs_Call {
	return &MockAchievementService_ReevalByDiffs_Call{Call: _e.mock.On("ReevalByDiffs", ruleDiffs)}
}

func (_c *MockAchievementService_ReevalByDiffs_Call) Run(run func(ruleDiffs *[]dto.RuleDiff)) *MockAchievementService_ReevalByDiffs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *[]dto.RuleDiff
		if args[0] != nil {
			arg0 = args[0].(*[]dto.RuleDiff)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAchievementService_ReevalByDiffs_Call) Return(err error) *MockAchievementService_ReevalByDiffs_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAchievementService_ReevalByDiffs_Call) RunAndReturn(run func(ruleDiffs *[]dto.RuleDiff) error) *MockAchievementService_ReevalByDiffs_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEventService creates a new instance of MockEventService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventService {
	mock := &MockEventService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEventService is an autogenerated mock type for the EventService type
type MockEventService struct {
	mock.Mock
}

type MockEventService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEventService) EXPECT() *MockEventService_Expecter {
	return &MockEventService_Expecter{mock: &_m.Mock}
}

// LoadUsersToCache provides a mock function for the type MockEventService
func (_mock *MockEventService) LoadUsersToCache(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for LoadUsersToCache")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEventService_LoadUsersToCache_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadUsersToCache'
type MockEventService_LoadUsersToCache_Call struct {
	*mock.Call
}

// LoadUsersToCache is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockEventService_Expecter) LoadUsersToCache(ctx interface{}) *MockEventService_LoadUsersToCache_Call {
	return &MockEventService_LoadUsersToCache_Call{Call: _e.mock.On("LoadUsersToCache", ctx)}
}

func (_c *MockEventService_LoadUsersToCache_Call) Run(run func(ctx context.Context)) *MockEventService_LoadUsersToCache_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEventService_LoadUsersToCache_Call) Return(err error) *MockEventService_LoadUsersToCache_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEventService_LoadUsersToCache_Call) RunAndReturn(run func(ctx context.Context) error) *MockEventService_LoadUsersToCache_Call {
	_c.Call.Return(run)
	return _c
}

// SaveAll provides a mock function for the type MockEventService
func (_mock *MockEventService) SaveAll(ctx context.Context, events *[]dto.Event) *api.APIError {
	ret := _mock.Called(ctx, events)

	if len(ret) == 0 {
		panic("no return value specified for SaveAll")
	}

	var r0 *api.APIError
	if returnFunc, ok := ret.Get(0).(func(context.Context, *[]dto.Event) *api.APIError); ok {
		r0 = returnFunc(ctx, events)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.APIError)
		}
	}
	return r0
}

// MockEventService_SaveAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveAll'
type MockEventService_SaveAll_Call struct {
	*mock.Call
}

// SaveAll is a helper method to define mock.On call
//   - ctx context.Context
//   - events *[]dto.Event
func (_e *MockEventService_Expecter) SaveAll(ctx interface{}, events interface{}) *MockEventService_SaveAll_Call {
	return &MockEventService_SaveAll_Call{Call: _e.mock.On("SaveAll", ctx, events)}
}

func (_c *MockEventService_SaveAll_Call) Run(run func(ctx context.Context, events *[]dto.Event)) *MockEventService_SaveAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *[]dto.Event
		if args[1] != nil {
			arg1 = args[1].(*[]dto.Event)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventService_SaveAll_Call) Return(aPIError *api.APIError) *MockEventService_SaveAll_Call {
	_c.Call.Return(aPIError)
	return _c
}

func (_c *MockEventService_SaveAll_Call) RunAndReturn(run func(ctx context.Context, events *[]dto.Event) *api.APIError) *MockEventService_SaveAll_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockNotificationService creates a new instance of MockNotificationService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNotificationService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNotificationService {
	mock := &MockNotificationService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockNotificationService is an autogenerated mock type for the NotificationService type
type MockNotificationService struct {
	mock.Mock
}

type MockNotificationService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNotificationService) EXPECT() *MockNotificationService_Expecter {
	return &MockNotificationService_Expecter{mock: &_m.Mock}
}

// Notify provides a mock function for the type MockNotificationService
func (_mock *MockNotificationService) Notify(notifications *[]dto.Notification) error {
	ret := _mock.Called(notifications)

	if len(ret) == 0 {
		panic("no return value specified for Notify")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*[]dto.Notification) error); ok {
		r0 = returnFunc(notifications)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNotificationService_Notify_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Notify'
type MockNotificationService_Notify_Call struct {
	*mock.Call
}

// Notify is a helper method to define mock.On call
//   - notifications *[]dto.Notification
func (_e *MockNotificationService_Expecter) Notify(notifications interface{}) *MockNotificationService_Notify_Call {
	return &MockNotificationService_Notify_Call{Call: _e.mock.On("Notify", notifications)}
}

func (_c *MockNotificationService_Notify_Call) Run(run func(notifications *[]dto.Notification)) *MockNotificationService_Notify_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *[]dto.Notification
		if args[0] != nil {
			arg0 = args[0].(*[]dto.Notification)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockNotificationService_Notify_Call) Return(err error) *MockNotificationService_Notify_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNotificationService_Notify_Call) RunAndReturn(run func(notifications *[]dto.Notification) error) *MockNotificationService_Notify_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRuleService creates a new instance of MockRuleService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRuleService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRuleService {
	mock := &MockRuleService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRuleService is an autogenerated mock type for the RuleService type
type MockRuleService struct {
	mock.Mock
}

type MockRuleService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRuleService) EXPECT() *MockRuleService_Expecter {
	return &MockRuleService_Expecter{mock: &_m.Mock}
}

// GetRulesDiffs provides a mock function for the type MockRuleService
func (_mock *MockRuleService) GetRulesDiffs(rules *[]dto.Rule) (*[]dto.RuleDiff, error) {
	ret := _mock.Called(rules)

	if len(ret) == 0 {
		panic("no return value specified for GetRulesDiffs")
	}

	var r0 *[]dto.RuleDiff
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*[]dto.Rule) (*[]dto.RuleDiff, error)); ok {
		return returnFunc(rules)
	}
	if returnFunc, ok := ret.Get(0).(func(*[]dto.Rule) *[]dto.RuleDiff); ok {
		r0 = returnFunc(rules)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]dto.RuleDiff)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*[]dto.Rule) error); ok {
		r1 = returnFunc(rules)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRuleService_GetRulesDiffs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRulesDiffs'
type MockRuleService_GetRulesDiffs_Call struct {
	*mock.Call
}

// GetRulesDiffs is a helper method to define mock.On call
//   - rules *[]dto.Rule
func (_e *MockRuleService_Expecter) GetRulesDiffs(rules interface{}) *MockRuleService_GetRulesDiffs_Call {
	return &MockRuleService_GetRulesDiffs_Call{Call: _e.mock.On("GetRulesDiffs", rules)}
}

func (_c *MockRuleService_GetRulesDiffs_Call) Run(run func(rules *[]dto.Rule)) *MockRuleService_GetRulesDiffs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *[]dto.Rule
		if args[0] != nil {
			arg0 = args[0].(*[]dto.Rule)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRuleService_GetRulesDiffs_Call) Return(ruleDiffs *[]dto.RuleDiff, err error) *MockRuleService_GetRulesDiffs_Call {
	_c.Call.Return(ruleDiffs, err)
	return _c
}

func (_c *MockRuleService_GetRulesDiffs_Call) RunAndReturn(run func(rules *[]dto.Rule) (*[]dto.RuleDiff, error)) *MockRuleService_GetRulesDiffs_Call {
	_c.Call.Return(run)
	return _c
}

// SaveAll provides a mock function for the type MockRuleService
func (_mock *MockRuleService) SaveAll(rules *[]dto.Rule) error {
	ret := _mock.Called(rules)

	if len(ret) == 0 {
		panic("no return value specified for SaveAll")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*[]dto.Rule) error); ok {
		r0 = returnFunc(rules)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRuleService_SaveAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveAll'
type MockRuleService_SaveAll_Call struct {
	*mock.Call
}

// SaveAll is a helper method to define mock.On call
//   - rules *[]dto.Rule
func (_e *MockRuleService_Expecter) SaveAll(rules interface{}) *MockRuleService_SaveAll_Call {
	return &MockRuleService_SaveAll_Call{Call: _e.mock.On("SaveAll", rules)}
}

func (_c *MockRuleService_SaveAll_Call) Run(run func(rules *[]dto.Rule)) *MockRuleService_SaveAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *[]dto.Rule
		if args[0] != nil {
			arg0 = args[0].(*[]dto.Rule)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRuleService_SaveAll_Call) Return(err error) *MockRuleService_SaveAll_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRuleService_SaveAll_Call) RunAndReturn(run func(rules *[]dto.Rule) error) *MockRuleService_SaveAll_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserService creates a new instance of MockUserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserService {
	mock := &MockUserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserService is an autogenerated mock type for the UserService type
type MockUserService struct {
	mock.Mock
}

type MockUserService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserService) EXPECT() *MockUserService_Expecter {
	return &MockUserService_Expecter{mock: &_m.Mock}
}

// Authenticate provides a mock function for the type MockUserService
func (_mock *MockUserService) Authenticate(email string, password string) *api.APIError {
	ret := _mock.Called(email, password)

	if len(ret) == 0 {
		panic("no return value specified for Authenticate")
	}

	var r0 *api.APIError
	if returnFunc, ok := ret.Get(0).(func(string, string) *api.APIError); ok {
		r0 = returnFunc(email, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.APIError)
		}
	}
	return r0
}

// MockUserService_Authenticate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Authenticate'
type MockUserService_Authenticate_Call struct {
	*mock.Call
}

// Authenticate is a helper method to define mock.On call
//   - email string
//   - password string
func (_e *MockUserService_Expecter) Authenticate(email interface{}, password interface{}) *MockUserService_Authenticate_Call {
	return &MockUserService_Authenticate_Call{Call: _e.mock.On("Authenticate", email, password)}
}

func (_c *MockUserService_Authenticate_Call) Run(run func(email string, password string)) *MockUserService_Authenticate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserService_Authenticate_Call) Return(aPIError *api.APIError) *MockUserService_Authenticate_Call {
	_c.Call.Return(aPIError)
	return _c
}

func (_c *MockUserService_Authenticate_Call) RunAndReturn(run func(email string, password string) *api.APIError) *MockUserService_Authenticate_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function for the type MockUserService
func (_mock *MockUserService) Register(email string, password string) (*uuid.UUID, *api.APIError) {
	ret := _mock.Called(email, password)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *uuid.UUID
	var r1 *api.APIError
	if returnFunc, ok := ret.Get(0).(func(string, string) (*uuid.UUID, *api.APIError)); ok {
		return returnFunc(email, password)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) *uuid.UUID); ok {
		r0 = returnFunc(email, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) *api.APIError); ok {
		r1 = returnFunc(email, password)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*api.APIError)
		}
	}
	return r0, r1
}

// MockUserService_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type MockUserService_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - email string
//   - password string
func (_e *MockUserService_Expecter) Register(email interface{}, password interface{}) *MockUserService_Register_Call {
	return &MockUserService_Register_Call{Call: _e.mock.On("Register", email, password)}
}

func (_c *MockUserService_Register_Call) Run(run func(email string, password string)) *MockUserService_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserService_Register_Call) Return(uUID *uuid.UUID, aPIError *api.APIError) *MockUserService_Register_Call {
	_c.Call.Return(uUID, aPIError)
	return _c
}

func (_c *MockUserService_Register_Call) RunAndReturn(run func(email string, password string) (*uuid.UUID, *api.APIError)) *MockUserService_Register_Call {
	_c.Call.Return(run)
	return _c
}
