// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package cache

import (
	"context"
	"time"

	"github.com/gabkaclassic/GitQuest/internal/dto"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAchievementCacheClient creates a new instance of MockAchievementCacheClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAchievementCacheClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAchievementCacheClient {
	mock := &MockAchievementCacheClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAchievementCacheClient is an autogenerated mock type for the AchievementCacheClient type
type MockAchievementCacheClient struct {
	mock.Mock
}

type MockAchievementCacheClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAchievementCacheClient) EXPECT() *MockAchievementCacheClient_Expecter {
	return &MockAchievementCacheClient_Expecter{mock: &_m.Mock}
}

// AchievementExists provides a mock function for the type MockAchievementCacheClient
func (_mock *MockAchievementCacheClient) AchievementExists(context1 context.Context, achievement *dto.Achievement) (bool, error) {
	ret := _mock.Called(context1, achievement)

	if len(ret) == 0 {
		panic("no return value specified for AchievementExists")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.Achievement) (bool, error)); ok {
		return returnFunc(context1, achievement)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dto.Achievement) bool); ok {
		r0 = returnFunc(context1, achievement)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dto.Achievement) error); ok {
		r1 = returnFunc(context1, achievement)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAchievementCacheClient_AchievementExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AchievementExists'
type MockAchievementCacheClient_AchievementExists_Call struct {
	*mock.Call
}

// AchievementExists is a helper method to define mock.On call
//   - context1 context.Context
//   - achievement *dto.Achievement
func (_e *MockAchievementCacheClient_Expecter) AchievementExists(context1 interface{}, achievement interface{}) *MockAchievementCacheClient_AchievementExists_Call {
	return &MockAchievementCacheClient_AchievementExists_Call{Call: _e.mock.On("AchievementExists", context1, achievement)}
}

func (_c *MockAchievementCacheClient_AchievementExists_Call) Run(run func(context1 context.Context, achievement *dto.Achievement)) *MockAchievementCacheClient_AchievementExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dto.Achievement
		if args[1] != nil {
			arg1 = args[1].(*dto.Achievement)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAchievementCacheClient_AchievementExists_Call) Return(b bool, err error) *MockAchievementCacheClient_AchievementExists_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockAchievementCacheClient_AchievementExists_Call) RunAndReturn(run func(context1 context.Context, achievement *dto.Achievement) (bool, error)) *MockAchievementCacheClient_AchievementExists_Call {
	_c.Call.Return(run)
	return _c
}

// SaveAll provides a mock function for the type MockAchievementCacheClient
func (_mock *MockAchievementCacheClient) SaveAll(context1 context.Context, achievements *[]dto.Achievement) error {
	ret := _mock.Called(context1, achievements)

	if len(ret) == 0 {
		panic("no return value specified for SaveAll")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *[]dto.Achievement) error); ok {
		r0 = returnFunc(context1, achievements)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAchievementCacheClient_SaveAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveAll'
type MockAchievementCacheClient_SaveAll_Call struct {
	*mock.Call
}

// SaveAll is a helper method to define mock.On call
//   - context1 context.Context
//   - achievements *[]dto.Achievement
func (_e *MockAchievementCacheClient_Expecter) SaveAll(context1 interface{}, achievements interface{}) *MockAchievementCacheClient_SaveAll_Call {
	return &MockAchievementCacheClient_SaveAll_Call{Call: _e.mock.On("SaveAll", context1, achievements)}
}

func (_c *MockAchievementCacheClient_SaveAll_Call) Run(run func(context1 context.Context, achievements *[]dto.Achievement)) *MockAchievementCacheClient_SaveAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *[]dto.Achievement
		if args[1] != nil {
			arg1 = args[1].(*[]dto.Achievement)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAchievementCacheClient_SaveAll_Call) Return(err error) *MockAchievementCacheClient_SaveAll_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAchievementCacheClient_SaveAll_Call) RunAndReturn(run func(context1 context.Context, achievements *[]dto.Achievement) error) *MockAchievementCacheClient_SaveAll_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEventCacheClient creates a new instance of MockEventCacheClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventCacheClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventCacheClient {
	mock := &MockEventCacheClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEventCacheClient is an autogenerated mock type for the EventCacheClient type
type MockEventCacheClient struct {
	mock.Mock
}

type MockEventCacheClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEventCacheClient) EXPECT() *MockEventCacheClient_Expecter {
	return &MockEventCacheClient_Expecter{mock: &_m.Mock}
}

// CleanupOldEventsFromCache provides a mock function for the type MockEventCacheClient
func (_mock *MockEventCacheClient) CleanupOldEventsFromCache(context1 context.Context) error {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for CleanupOldEventsFromCache")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(context1)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEventCacheClient_CleanupOldEventsFromCache_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CleanupOldEventsFromCache'
type MockEventCacheClient_CleanupOldEventsFromCache_Call struct {
	*mock.Call
}

// CleanupOldEventsFromCache is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockEventCacheClient_Expecter) CleanupOldEventsFromCache(context1 interface{}) *MockEventCacheClient_CleanupOldEventsFromCache_Call {
	return &MockEventCacheClient_CleanupOldEventsFromCache_Call{Call: _e.mock.On("CleanupOldEventsFromCache", context1)}
}

func (_c *MockEventCacheClient_CleanupOldEventsFromCache_Call) Run(run func(context1 context.Context)) *MockEventCacheClient_CleanupOldEventsFromCache_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEventCacheClient_CleanupOldEventsFromCache_Call) Return(err error) *MockEventCacheClient_CleanupOldEventsFromCache_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEventCacheClient_CleanupOldEventsFromCache_Call) RunAndReturn(run func(context1 context.Context) error) *MockEventCacheClient_CleanupOldEventsFromCache_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserEventsTimestampsByTypeAndRange provides a mock function for the type MockEventCacheClient
func (_mock *MockEventCacheClient) GetUserEventsTimestampsByTypeAndRange(context1 context.Context, s string, eventType dto.EventType, time1 time.Time, time11 time.Time) (*[]time.Time, error) {
	ret := _mock.Called(context1, s, eventType, time1, time11)

	if len(ret) == 0 {
		panic("no return value specified for GetUserEventsTimestampsByTypeAndRange")
	}

	var r0 *[]time.Time
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, dto.EventType, time.Time, time.Time) (*[]time.Time, error)); ok {
		return returnFunc(context1, s, eventType, time1, time11)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, dto.EventType, time.Time, time.Time) *[]time.Time); ok {
		r0 = returnFunc(context1, s, eventType, time1, time11)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]time.Time)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, dto.EventType, time.Time, time.Time) error); ok {
		r1 = returnFunc(context1, s, eventType, time1, time11)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEventCacheClient_GetUserEventsTimestampsByTypeAndRange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserEventsTimestampsByTypeAndRange'
type MockEventCacheClient_GetUserEventsTimestampsByTypeAndRange_Call struct {
	*mock.Call
}

// GetUserEventsTimestampsByTypeAndRange is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
//   - eventType dto.EventType
//   - time1 time.Time
//   - time11 time.Time
func (_e *MockEventCacheClient_Expecter) GetUserEventsTimestampsByTypeAndRange(context1 interface{}, s interface{}, eventType interface{}, time1 interface{}, time11 interface{}) *MockEventCacheClient_GetUserEventsTimestampsByTypeAndRange_Call {
	return &MockEventCacheClient_GetUserEventsTimestampsByTypeAndRange_Call{Call: _e.mock.On("GetUserEventsTimestampsByTypeAndRange", context1, s, eventType, time1, time11)}
}

func (_c *MockEventCacheClient_GetUserEventsTimestampsByTypeAndRange_Call) Run(run func(context1 context.Context, s string, eventType dto.EventType, time1 time.Time, time11 time.Time)) *MockEventCacheClient_GetUserEventsTimestampsByTypeAndRange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 dto.EventType
		if args[2] != nil {
			arg2 = args[2].(dto.EventType)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		var arg4 time.Time
		if args[4] != nil {
			arg4 = args[4].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockEventCacheClient_GetUserEventsTimestampsByTypeAndRange_Call) Return(times *[]time.Time, err error) *MockEventCacheClient_GetUserEventsTimestampsByTypeAndRange_Call {
	_c.Call.Return(times, err)
	return _c
}

func (_c *MockEventCacheClient_GetUserEventsTimestampsByTypeAndRange_Call) RunAndReturn(run func(context1 context.Context, s string, eventType dto.EventType, time1 time.Time, time11 time.Time) (*[]time.Time, error)) *MockEventCacheClient_GetUserEventsTimestampsByTypeAndRange_Call {
	_c.Call.Return(run)
	return _c
}

// SaveNewEvents provides a mock function for the type MockEventCacheClient
func (_mock *MockEventCacheClient) SaveNewEvents(context1 context.Context, events *[]dto.Event) (*[]string, error) {
	ret := _mock.Called(context1, events)

	if len(ret) == 0 {
		panic("no return value specified for SaveNewEvents")
	}

	var r0 *[]string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *[]dto.Event) (*[]string, error)); ok {
		return returnFunc(context1, events)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *[]dto.Event) *[]string); ok {
		r0 = returnFunc(context1, events)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *[]dto.Event) error); ok {
		r1 = returnFunc(context1, events)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEventCacheClient_SaveNewEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveNewEvents'
type MockEventCacheClient_SaveNewEvents_Call struct {
	*mock.Call
}

// SaveNewEvents is a helper method to define mock.On call
//   - context1 context.Context
//   - events *[]dto.Event
func (_e *MockEventCacheClient_Expecter) SaveNewEvents(context1 interface{}, events interface{}) *MockEventCacheClient_SaveNewEvents_Call {
	return &MockEventCacheClient_SaveNewEvents_Call{Call: _e.mock.On("SaveNewEvents", context1, events)}
}

func (_c *MockEventCacheClient_SaveNewEvents_Call) Run(run func(context1 context.Context, events *[]dto.Event)) *MockEventCacheClient_SaveNewEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *[]dto.Event
		if args[1] != nil {
			arg1 = args[1].(*[]dto.Event)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventCacheClient_SaveNewEvents_Call) Return(strings *[]string, err error) *MockEventCacheClient_SaveNewEvents_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockEventCacheClient_SaveNewEvents_Call) RunAndReturn(run func(context1 context.Context, events *[]dto.Event) (*[]string, error)) *MockEventCacheClient_SaveNewEvents_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUserCacheClient creates a new instance of MockUserCacheClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserCacheClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserCacheClient {
	mock := &MockUserCacheClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserCacheClient is an autogenerated mock type for the UserCacheClient type
type MockUserCacheClient struct {
	mock.Mock
}

type MockUserCacheClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserCacheClient) EXPECT() *MockUserCacheClient_Expecter {
	return &MockUserCacheClient_Expecter{mock: &_m.Mock}
}

// GetAll provides a mock function for the type MockUserCacheClient
func (_mock *MockUserCacheClient) GetAll(context1 context.Context) (*[]string, error) {
	ret := _mock.Called(context1)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 *[]string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*[]string, error)); ok {
		return returnFunc(context1)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *[]string); ok {
		r0 = returnFunc(context1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(context1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserCacheClient_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type MockUserCacheClient_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - context1 context.Context
func (_e *MockUserCacheClient_Expecter) GetAll(context1 interface{}) *MockUserCacheClient_GetAll_Call {
	return &MockUserCacheClient_GetAll_Call{Call: _e.mock.On("GetAll", context1)}
}

func (_c *MockUserCacheClient_GetAll_Call) Run(run func(context1 context.Context)) *MockUserCacheClient_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserCacheClient_GetAll_Call) Return(strings *[]string, err error) *MockUserCacheClient_GetAll_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockUserCacheClient_GetAll_Call) RunAndReturn(run func(context1 context.Context) (*[]string, error)) *MockUserCacheClient_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockUserCacheClient
func (_mock *MockUserCacheClient) Save(context1 context.Context, s string) error {
	ret := _mock.Called(context1, s)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(context1, s)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserCacheClient_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockUserCacheClient_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - context1 context.Context
//   - s string
func (_e *MockUserCacheClient_Expecter) Save(context1 interface{}, s interface{}) *MockUserCacheClient_Save_Call {
	return &MockUserCacheClient_Save_Call{Call: _e.mock.On("Save", context1, s)}
}

func (_c *MockUserCacheClient_Save_Call) Run(run func(context1 context.Context, s string)) *MockUserCacheClient_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserCacheClient_Save_Call) Return(err error) *MockUserCacheClient_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserCacheClient_Save_Call) RunAndReturn(run func(context1 context.Context, s string) error) *MockUserCacheClient_Save_Call {
	_c.Call.Return(run)
	return _c
}

// SaveAll provides a mock function for the type MockUserCacheClient
func (_mock *MockUserCacheClient) SaveAll(context1 context.Context, strings *[]string) error {
	ret := _mock.Called(context1, strings)

	if len(ret) == 0 {
		panic("no return value specified for SaveAll")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *[]string) error); ok {
		r0 = returnFunc(context1, strings)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserCacheClient_SaveAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveAll'
type MockUserCacheClient_SaveAll_Call struct {
	*mock.Call
}

// SaveAll is a helper method to define mock.On call
//   - context1 context.Context
//   - strings *[]string
func (_e *MockUserCacheClient_Expecter) SaveAll(context1 interface{}, strings interface{}) *MockUserCacheClient_SaveAll_Call {
	return &MockUserCacheClient_SaveAll_Call{Call: _e.mock.On("SaveAll", context1, strings)}
}

func (_c *MockUserCacheClient_SaveAll_Call) Run(run func(context1 context.Context, strings *[]string)) *MockUserCacheClient_SaveAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *[]string
		if args[1] != nil {
			arg1 = args[1].(*[]string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockUserCacheClient_SaveAll_Call) Return(err error) *MockUserCacheClient_SaveAll_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserCacheClient_SaveAll_Call) RunAndReturn(run func(context1 context.Context, strings *[]string) error) *MockUserCacheClient_SaveAll_Call {
	_c.Call.Return(run)
	return _c
}
